import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next.js Awesome Memo App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="kr">
      <body>{children}</body>
    </html>
  )
}
