import './globals.css'
import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Next.js Awesome Memo App',
  description: 'Generated by create next app',
}

const NotoSansKR = Noto_Sans_KR({
  weight: ['400', '700'],
  subsets: ['latin'],
  preload: true,
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="kr">
      <body className={NotoSansKR.className}>{children}</body>
    </html>
  )
}
